app/cookies.server.ts, app/routes/$cluster.tsx, app/routes/index.tsx
=> fix(app): redirect based on `cluster` cookie

.gitignore, research/hive-vs-rekt-influencers/Rekt-vs-Hive-influencer-comparison.ipynb, research/hive-vs-rekt-influencers/rekt_parlor.html, research/hive-vs-rekt-influencers/requirements.txt
Adding research folder for experiments or general notes about topics we are interested in. 
The notebook added here compares Hive Eth influencers to list of users in [rekt's crypto parlor](https://feed.rekt.news/parlor)
=> chore(research): add jupyter notebooks

app/components/article.tsx
=> fix(article): only transition transform scaling

app/routes/$cluster.tsx
=> fix($cluster): `await` cluster cookie serialization

app/components/article.tsx, app/root.tsx, app/routes/$cluster.tsx, scripts/metadata.mjs
=> feat: add order by tweets count

app/components/article.tsx, app/db.server.ts, app/routes/$cluster.tsx
=> feat: add sorting to tweets list

app/components/article.tsx, app/db.server.ts, app/routes/$cluster.tsx, scripts/metadata.mjs
=> feat: add show/hide retweets filters

app/routes/$cluster.tsx
Fixes TS-38:
Here's the problem: because certain influencers (e.g. Elon Musk and Tesla) have
scores for multiple clusters.id, whenever the select distinct happens to use the
row that has a different clusters.slug than the one that we're querying for
(e.g. if the @elonmusk row uses his attention_score for DogeCoin but we're
querying for articles about Tesla, all of Elon's tweets will be omitted from the
results).
The fix: select distinct on (urls.link_id, tweets.author_id, tweets.cluster_id
so that I get all of the rows that have unique links, authors, and clusters.
Then, the remaining of the query filters for a specific cluster so no duplicate
tweets (from the same author for the same link but with a different cluster's
score) should show up.
=> fix($cluster): query tweets from all influencers

app/components/empty.tsx, app/components/footer.tsx, app/components/header.tsx, app/root.tsx, app/routes/$cluster.tsx
=> feat: add custom root error boundary

.github/workflows/build.yml, .gitignore, app/components/article.tsx, app/components/tweet.tsx, app/cookies.server.ts, app/img.server.ts, app/root.tsx, cypress/support/index.ts, tsconfig.json
=> ci(build): setup type checking

app/components/tweet.tsx, app/icons/like.tsx, app/icons/reply.tsx, app/icons/twitter.tsx
=> feat(tweet): add like and reply links

app/db.server.ts, app/root.tsx, app/routes/$cluster.tsx
=> fix: address postgres pooling errors

README.md, pgbouncer/fly.toml, pghero/fly.toml
Fixes the real problems behind [TS-44](https://linear.app/roote/issue/TS-44/re-evaluate-deployment-tech-stack) without changing tech stacks.
=> perf: use `pgbouncer` on fly

app/root.tsx
=> fix(app/root): wait 500ms before `nprogress`

app/components/empty.tsx, app/components/header.tsx, app/db.server.ts, app/img.server.ts, app/utils.server.ts
=> refactor(app): use `import type` when appropriate

app/components/nav.tsx, app/routes/$cluster.tsx
=> feat: add nested error boundary

app/cookies.server.ts, app/routes/$cluster.tsx, app/routes/index.tsx
=> feat(app): save search params for redirect

app/components/header.tsx, app/components/sync.tsx, app/logout.server.ts, app/routes/logout.ts
=> feat: add logout button

app/limit.server.ts, app/redis.server.ts, app/swr.server.ts, app/types.ts, db/setup.pgsql, prisma/schema.prisma
=> feat: use redis to store rate limits

app/components/header.tsx, app/components/nav.tsx, app/components/tweet.tsx, app/icons/menu-open.tsx, app/icons/menu.tsx, app/routes/$src.$id.tsx
=> feat: add mobile viewport support

app/components/tweet.tsx, app/query.server.ts, app/types.ts
=> feat: show retweets like twitter

app/components/article.tsx, app/components/tweet.tsx, app/query.server.ts, app/routes/$src.$id/$.tsx, app/types.ts
=> feat: nest quoted tweets in feed

app/components/header.tsx, app/components/profile.tsx, app/lists.server.ts, app/query.server.ts, app/routes/$src.$id.tsx, db/setup.pgsql, prisma/schema.prisma, scripts/metadata.mjs, scripts/rekt.mjs, scripts/shared.mjs
=> feat: add rekt as data source

app/icons/time.tsx, app/query.server.ts, app/query.ts, app/routes/$src.$id/tweets.tsx
=> feat: add time window filters

app/routes/changelog.tsx
@nicholaschiang super quick change: adding subscribe link to your changelog's newsletter!
=> feat: add newsletter subscribe link
